#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.3.3 effective-5.10 (swiftlang-6.3.3.1.3 clang-2100.1.1.101)
#ifndef HERESDKEXPLORENATIVEBRIDGE_SWIFT_H
#define HERESDKEXPLORENATIVEBRIDGE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="HereSdkExploreNativeBridge",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="HereSdkExploreNativeBridge",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
/// ObjC-visible wrapper for Address.
SWIFT_CLASS_NAMED("HereAddress")
@interface HereAddress : NSObject
@property (nonatomic, copy) NSString * _Nonnull street;
@property (nonatomic, copy) NSString * _Nonnull houseNumber;
@property (nonatomic, copy) NSString * _Nonnull city;
@property (nonatomic, copy) NSString * _Nonnull district;
@property (nonatomic, copy) NSString * _Nonnull state;
@property (nonatomic, copy) NSString * _Nonnull countryCode;
@property (nonatomic, copy) NSString * _Nonnull countryName;
@property (nonatomic, copy) NSString * _Nonnull postalCode;
- (nonnull instancetype)initWithStreet:(NSString * _Nonnull)street houseNumber:(NSString * _Nonnull)houseNumber city:(NSString * _Nonnull)city district:(NSString * _Nonnull)district state:(NSString * _Nonnull)state countryCode:(NSString * _Nonnull)countryCode countryName:(NSString * _Nonnull)countryName postalCode:(NSString * _Nonnull)postalCode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible wrapper for MapCamera.State (nested struct).
SWIFT_CLASS_NAMED("HereCameraState")
@interface HereCameraState : NSObject
@property (nonatomic) double targetLatitude;
@property (nonatomic) double targetLongitude;
@property (nonatomic) double bearing;
@property (nonatomic) double tilt;
@property (nonatomic) double distanceToTargetInMeters;
@property (nonatomic) double zoomLevel;
- (nonnull instancetype)initWithTargetLatitude:(double)targetLatitude targetLongitude:(double)targetLongitude bearing:(double)bearing tilt:(double)tilt distanceToTargetInMeters:(double)distanceToTargetInMeters zoomLevel:(double)zoomLevel OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible delegate for double tap gestures.
SWIFT_PROTOCOL_NAMED("HereDoubleTapDelegate")
@protocol HereDoubleTapDelegate
- (void)onDoubleTapWithOriginX:(double)originX originY:(double)originY;
@end

@class HereGeoCoordinates;
/// ObjC-visible wrapper for GeoBox.
SWIFT_CLASS_NAMED("HereGeoBox")
@interface HereGeoBox : NSObject
@property (nonatomic, strong) HereGeoCoordinates * _Nonnull southWest;
@property (nonatomic, strong) HereGeoCoordinates * _Nonnull northEast;
- (nonnull instancetype)initWithSouthWest:(HereGeoCoordinates * _Nonnull)southWest northEast:(HereGeoCoordinates * _Nonnull)northEast OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible wrapper for GeoCoordinates (Swift struct → ObjC class).
SWIFT_CLASS_NAMED("HereGeoCoordinates")
@interface HereGeoCoordinates : NSObject
@property (nonatomic) double latitude;
@property (nonatomic) double longitude;
- (nonnull instancetype)initWithLatitude:(double)latitude longitude:(double)longitude OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible wrapper for GeoPolygon.
SWIFT_CLASS_NAMED("HereGeoPolygon")
@interface HereGeoPolygon : NSObject
@property (nonatomic, copy) NSArray<HereGeoCoordinates *> * _Nonnull vertices;
- (nonnull instancetype)initWithVertices:(NSArray<HereGeoCoordinates *> * _Nonnull)vertices OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible wrapper for GeoPolyline.
SWIFT_CLASS_NAMED("HereGeoPolyline")
@interface HereGeoPolyline : NSObject
@property (nonatomic, copy) NSArray<HereGeoCoordinates *> * _Nonnull vertices;
- (nonnull instancetype)initWithVertices:(NSArray<HereGeoCoordinates *> * _Nonnull)vertices OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class HereMapBridgeView;
@protocol HereTapDelegate;
@protocol HereLongPressDelegate;
/// ObjC-visible wrapper for Gestures.
SWIFT_CLASS_NAMED("HereGestures")
@interface HereGestures : NSObject
/// @objc factory — creates from the bridge view which holds the MapView.
- (nonnull instancetype)initWithBridgeView:(HereMapBridgeView * _Nonnull)bridgeView;
- (void)setTapDelegate:(id <HereTapDelegate> _Nullable)delegate;
- (void)setLongPressDelegate:(id <HereLongPressDelegate> _Nullable)delegate;
- (void)setDoubleTapDelegate:(id <HereDoubleTapDelegate> _Nullable)delegate;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible wrapper for InstantiationErrorCode (UInt32 → NSInteger).
typedef SWIFT_ENUM_NAMED(NSInteger, HereInstantiationErrorCode, "HereInstantiationErrorCode", open) {
  HereInstantiationErrorCodeNone = 0,
  HereInstantiationErrorCodeNetworkError = 1,
  HereInstantiationErrorCodeInvalidCredentials = 2,
  HereInstantiationErrorCodeInvalidOptions = 3,
  HereInstantiationErrorCodeAlreadyInitialized = 4,
  HereInstantiationErrorCodeEngineDisposed = 5,
  HereInstantiationErrorCodeInternalError = 6,
};

/// ObjC-visible wrapper for Isoline.
SWIFT_CLASS_NAMED("HereIsoline")
@interface HereIsoline : NSObject
@property (nonatomic) double rangeValue;
@property (nonatomic, copy) NSArray<HereGeoCoordinates *> * _Nonnull polygonVertices;
- (nonnull instancetype)initWithRangeValue:(double)rangeValue polygonVertices:(NSArray<HereGeoCoordinates *> * _Nonnull)polygonVertices OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible isoline result.
SWIFT_CLASS_NAMED("HereIsolineResult")
@interface HereIsolineResult : NSObject
@property (nonatomic, copy) NSString * _Nullable error;
@property (nonatomic, copy) NSArray<HereIsoline *> * _Nullable isolines;
- (nonnull instancetype)initWithError:(NSString * _Nullable)error isolines:(NSArray<HereIsoline *> * _Nullable)isolines OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible wrapper for IsolineRoutingEngine.
SWIFT_CLASS_NAMED("HereIsolineRoutingEngine")
@interface HereIsolineRoutingEngine : NSObject
- (nonnull instancetype)initWithSdkEnginePointer:(int64_t)sdkEnginePointer OBJC_DESIGNATED_INITIALIZER;
/// Calculates an isoline around a center point.
/// \param transportMode 0=Car, 1=Truck, 2=Pedestrian, 3=Bicycle, 4=Scooter (see HereRoutingOptions)
///
/// \param rangeInMeters reachability range in meters
///
/// \param maxPoints maximum polygon points; 0 means SDK default
///
- (void)calculateIsolineWithCenterLatitude:(double)centerLatitude centerLongitude:(double)centerLongitude transportMode:(NSInteger)transportMode rangeInMeters:(int32_t)rangeInMeters maxPoints:(int32_t)maxPoints completion:(void (^ _Nonnull)(HereIsolineResult * _Nonnull))completion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible wrapper for Location (Swift struct → ObjC class).
SWIFT_CLASS_NAMED("HereLocation")
@interface HereLocation : NSObject
@property (nonatomic) double latitude;
@property (nonatomic) double longitude;
@property (nonatomic) double speedInMetersPerSecond;
@property (nonatomic) double bearingInDegrees;
@property (nonatomic) int64_t timestampInMilliseconds;
- (nonnull instancetype)initWithLatitude:(double)latitude longitude:(double)longitude speedInMetersPerSecond:(double)speedInMetersPerSecond bearingInDegrees:(double)bearingInDegrees timestampInMilliseconds:(int64_t)timestampInMilliseconds OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible delegate for long press gestures.
/// Includes gesture state (begin/update/end) as an integer: 0=begin, 1=update, 2=end.
SWIFT_PROTOCOL_NAMED("HereLongPressDelegate")
@protocol HereLongPressDelegate
- (void)onLongPressWithState:(NSInteger)state originX:(double)originX originY:(double)originY;
@end

/// ObjC-visible wrapper for Maneuver.
SWIFT_CLASS_NAMED("HereManeuver")
@interface HereManeuver : NSObject
@property (nonatomic, strong) HereGeoCoordinates * _Nonnull coordinates;
@property (nonatomic) NSInteger action;
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic) int32_t lengthInMeters;
@property (nonatomic) double durationInSeconds;
@property (nonatomic) double turnAngleInDegrees;
- (nonnull instancetype)initWithCoordinates:(HereGeoCoordinates * _Nonnull)coordinates action:(NSInteger)action text:(NSString * _Nullable)text lengthInMeters:(int32_t)lengthInMeters durationInSeconds:(double)durationInSeconds turnAngleInDegrees:(double)turnAngleInDegrees OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIColor;
/// ObjC-visible wrapper for MapArrow.
SWIFT_CLASS_NAMED("HereMapArrow")
@interface HereMapArrow : NSObject
- (nonnull instancetype)initWithVertices:(NSArray<HereGeoCoordinates *> * _Nonnull)vertices widthInPixels:(double)widthInPixels color:(UIColor * _Nonnull)color OBJC_DESIGNATED_INITIALIZER;
- (void)addToMapView:(HereMapBridgeView * _Nonnull)mapView;
- (void)removeFromMapView:(HereMapBridgeView * _Nonnull)mapView;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIView;
/// ObjC-visible UIView wrapper that owns a HERE MapView.
/// C# uses this as the platform view for the MAUI handler.
/// Other NativeBridge wrappers (HereMapCamera, HereMapScene, HereGestures)
/// extract MapView/mapScene/camera/gestures from this bridge view.
SWIFT_CLASS_NAMED("HereMapBridgeView")
@interface HereMapBridgeView : NSObject
/// @objc factory — C# calls this to create a bridge that owns the MapView.
+ (HereMapBridgeView * _Nonnull)create SWIFT_WARN_UNUSED_RESULT;
/// Expose the MapView as a UIView for C# handlers.
@property (nonatomic, readonly, strong) UIView * _Nullable platformView;
/// Convert screen coordinates to geo coordinates.
- (HereGeoCoordinates * _Nullable)viewToGeoCoordinatesWithOriginX:(double)originX originY:(double)originY SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol HereMapCameraDelegate;
/// ObjC-visible wrapper for MapCamera.
SWIFT_CLASS_NAMED("HereMapCamera")
@interface HereMapCamera : NSObject
/// @objc factory — creates from the bridge view which holds the MapView.
- (nonnull instancetype)initWithBridgeView:(HereMapBridgeView * _Nonnull)bridgeView;
@property (nonatomic, readonly, strong) HereCameraState * _Nonnull state;
- (void)setTarget:(HereGeoCoordinates * _Nonnull)coordinates;
- (void)setTarget:(HereGeoCoordinates * _Nonnull)coordinates zoomLevel:(double)zoomLevel;
- (void)addDelegate:(id <HereMapCameraDelegate> _Nonnull)delegate;
- (void)removeDelegate;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible delegate for MapCamera updates.
SWIFT_PROTOCOL_NAMED("HereMapCameraDelegate")
@protocol HereMapCameraDelegate
@optional
- (void)onMapCameraUpdated:(HereCameraState * _Nonnull)cameraState;
@end

/// ObjC-visible wrapper for MapMarker.
SWIFT_CLASS_NAMED("HereMapMarker")
@interface HereMapMarker : NSObject
@property (nonatomic) double latitude;
@property (nonatomic) double longitude;
@property (nonatomic, copy) NSString * _Nullable imageName;
- (nonnull instancetype)initWithLatitude:(double)latitude longitude:(double)longitude OBJC_DESIGNATED_INITIALIZER;
/// Create with image name (for MapScene-based add/remove).
- (nonnull instancetype)initWithLatitude:(double)latitude longitude:(double)longitude imageName:(NSString * _Nonnull)imageName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible wrapper for MapMarker3D.
/// Supports both image-based and model-based 3D markers.
SWIFT_CLASS_NAMED("HereMapMarker3D")
@interface HereMapMarker3D : NSObject
@property (nonatomic) double bearing;
@property (nonatomic) double scale;
/// Create a 3D marker with an image (billboard-style).
- (nonnull instancetype)initWithLatitude:(double)latitude longitude:(double)longitude imageName:(NSString * _Nonnull)imageName width:(int32_t)width height:(int32_t)height scale:(double)scale OBJC_DESIGNATED_INITIALIZER;
- (void)addToMapView:(HereMapBridgeView * _Nonnull)mapView;
- (void)removeFromMapView:(HereMapBridgeView * _Nonnull)mapView;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible wrapper for MapPolygon.
SWIFT_CLASS_NAMED("HereMapPolygon")
@interface HereMapPolygon : NSObject
@property (nonatomic) int32_t drawOrder;
- (nonnull instancetype)initWithVertices:(NSArray<HereGeoCoordinates *> * _Nonnull)vertices fillColor:(UIColor * _Nonnull)fillColor OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithVertices:(NSArray<HereGeoCoordinates *> * _Nonnull)vertices fillColor:(UIColor * _Nonnull)fillColor outlineColor:(UIColor * _Nonnull)outlineColor outlineWidthInPixels:(double)outlineWidthInPixels OBJC_DESIGNATED_INITIALIZER;
- (void)addToMapView:(HereMapBridgeView * _Nonnull)mapView;
- (void)removeFromMapView:(HereMapBridgeView * _Nonnull)mapView;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible wrapper for MapPolyline.
/// MapPolyline uses the Representation pattern for styling.
SWIFT_CLASS_NAMED("HereMapPolyline")
@interface HereMapPolyline : NSObject
@property (nonatomic) int32_t drawOrder;
/// Creates a solid-color polyline with the given vertices, color, and width.
- (nonnull instancetype)initWithVertices:(NSArray<HereGeoCoordinates *> * _Nonnull)vertices color:(UIColor * _Nonnull)color widthInPixels:(double)widthInPixels OBJC_DESIGNATED_INITIALIZER;
- (void)addToMapView:(HereMapBridgeView * _Nonnull)mapView;
- (void)removeFromMapView:(HereMapBridgeView * _Nonnull)mapView;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_ENUM_FWD_DECL(NSInteger, HereMapScheme)
@protocol HereSceneLoadCallback;
/// ObjC-visible wrapper for MapScene.
SWIFT_CLASS_NAMED("HereMapScene")
@interface HereMapScene : NSObject
/// @objc factory — creates from the bridge view which holds the MapView.
- (nonnull instancetype)initWithBridgeView:(HereMapBridgeView * _Nonnull)bridgeView;
- (void)loadScene:(enum HereMapScheme)scheme;
- (void)setCallback:(id <HereSceneLoadCallback> _Nonnull)callback;
- (void)addMapMarker:(HereMapMarker * _Nonnull)marker;
- (void)removeMapMarker:(HereMapMarker * _Nonnull)marker;
- (void)addMapMarker3D:(HereMapMarker3D * _Nonnull)marker;
- (void)removeMapMarker3D:(HereMapMarker3D * _Nonnull)marker;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible NSInteger enum wrapper for MapScheme (which is UInt32-backed in Swift).
typedef SWIFT_ENUM_NAMED(NSInteger, HereMapScheme, "HereMapScheme", open) {
  HereMapSchemeNormalDay = 0,
  HereMapSchemeNormalNight = 1,
  HereMapSchemeSatellite = 2,
  HereMapSchemeHybridDay = 3,
  HereMapSchemeHybridNight = 4,
  HereMapSchemeLiteDay = 5,
  HereMapSchemeLiteNight = 6,
  HereMapSchemeLiteHybridDay = 7,
  HereMapSchemeLiteHybridNight = 8,
  HereMapSchemeLogisticsDay = 9,
  HereMapSchemeLogisticsNight = 10,
  HereMapSchemeLogisticsHybridDay = 11,
  HereMapSchemeLogisticsHybridNight = 12,
  HereMapSchemeRoadNetworkDay = 13,
  HereMapSchemeRoadNetworkNight = 14,
};

/// ObjC-visible wrapper for Place (search result).
SWIFT_CLASS_NAMED("HerePlace")
@interface HerePlace : NSObject
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic) double latitude;
@property (nonatomic) double longitude;
@property (nonatomic, strong) HereAddress * _Nullable address;
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id title:(NSString * _Nonnull)title latitude:(double)latitude longitude:(double)longitude address:(HereAddress * _Nullable)address OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible wrapper for Point2D (Swift struct → ObjC class).
SWIFT_CLASS_NAMED("HerePoint2D")
@interface HerePoint2D : NSObject
@property (nonatomic) double x;
@property (nonatomic) double y;
- (nonnull instancetype)initWithX:(double)x y:(double)y OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class HereSection;
/// ObjC-visible wrapper for Route.
SWIFT_CLASS_NAMED("HereRoute")
@interface HereRoute : NSObject
@property (nonatomic) int32_t lengthInMeters;
@property (nonatomic) double durationInSeconds;
@property (nonatomic, copy) NSString * _Nullable routeHandle;
@property (nonatomic, copy) NSArray<HereSection *> * _Nullable sections;
@property (nonatomic, strong) HereGeoPolyline * _Nullable geometry;
- (nonnull instancetype)initWithLengthInMeters:(int32_t)lengthInMeters durationInSeconds:(double)durationInSeconds routeHandle:(NSString * _Nullable)routeHandle sections:(NSArray<HereSection *> * _Nullable)sections geometry:(HereGeoPolyline * _Nullable)geometry OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible route result.
SWIFT_CLASS_NAMED("HereRouteResult")
@interface HereRouteResult : NSObject
@property (nonatomic, copy) NSString * _Nullable error;
@property (nonatomic, copy) NSArray<HereRoute *> * _Nullable routes;
- (nonnull instancetype)initWithError:(NSString * _Nullable)error routes:(NSArray<HereRoute *> * _Nullable)routes OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class HereWaypoint;
@class HereRoutingOptions;
/// ObjC-visible wrapper for RoutingEngine.
SWIFT_CLASS_NAMED("HereRoutingEngine")
@interface HereRoutingEngine : NSObject
- (nonnull instancetype)initWithSdkEnginePointer:(int64_t)sdkEnginePointer OBJC_DESIGNATED_INITIALIZER;
- (void)calculateRouteWithWaypoints:(NSArray<HereWaypoint *> * _Nonnull)waypoints options:(HereRoutingOptions * _Nonnull)options completion:(void (^ _Nonnull)(HereRouteResult * _Nonnull))completion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible wrapper for RoutingOptions.
/// Uses TransportSpecification (the new v4.28+ pattern).
SWIFT_CLASS_NAMED("HereRoutingOptions")
@interface HereRoutingOptions : NSObject
@property (nonatomic) NSInteger transportMode;
- (nonnull instancetype)initWithTransportMode:(NSInteger)transportMode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Callback for scene load completion.
SWIFT_PROTOCOL_NAMED("HereSceneLoadCallback")
@protocol HereSceneLoadCallback
- (void)onSceneLoaded:(enum HereMapScheme)scheme;
- (void)onSceneLoadFailed:(NSString * _Nonnull)error;
@end

@class HereSdkOptions;
/// ObjC-visible wrapper for HERE SDK engine initialization.
SWIFT_CLASS_NAMED("HereSdkEngine")
@interface HereSdkEngine : NSObject
+ (void)initialize:(HereSdkOptions * _Nonnull)options;
+ (void)shutdown;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// ObjC-visible wrapper for HERE SDK options (initialization).
SWIFT_CLASS_NAMED("HereSdkOptions")
@interface HereSdkOptions : NSObject
@property (nonatomic, copy) NSString * _Nonnull accessKeyId;
@property (nonatomic, copy) NSString * _Nonnull accessKeySecret;
@property (nonatomic, copy) NSString * _Nullable cachePath;
- (nonnull instancetype)initWithAccessKeyId:(NSString * _Nonnull)accessKeyId accessKeySecret:(NSString * _Nonnull)accessKeySecret cachePath:(NSString * _Nullable)cachePath OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class HereSuggestion;
/// ObjC-visible wrapper for SearchEngine.
SWIFT_CLASS_NAMED("HereSearchEngine")
@interface HereSearchEngine : NSObject
- (nonnull instancetype)initWithSdkEnginePointer:(int64_t)sdkEnginePointer OBJC_DESIGNATED_INITIALIZER;
- (void)searchByTextWithQuery:(NSString * _Nonnull)query latitude:(double)latitude longitude:(double)longitude maxItems:(int32_t)maxItems languageCode:(NSInteger)languageCode completion:(void (^ _Nonnull)(NSArray<HerePlace *> * _Nullable, NSString * _Nullable))completion;
- (void)searchByCategoryWithCategoryId:(NSString * _Nonnull)categoryId latitude:(double)latitude longitude:(double)longitude maxItems:(int32_t)maxItems languageCode:(NSInteger)languageCode completion:(void (^ _Nonnull)(NSArray<HerePlace *> * _Nullable, NSString * _Nullable))completion;
- (void)suggestWithQuery:(NSString * _Nonnull)query latitude:(double)latitude longitude:(double)longitude maxItems:(int32_t)maxItems languageCode:(NSInteger)languageCode completion:(void (^ _Nonnull)(NSArray<HereSuggestion *> * _Nullable, NSString * _Nullable))completion;
- (void)searchByAddressWithQuery:(NSString * _Nonnull)query latitude:(double)latitude longitude:(double)longitude maxItems:(int32_t)maxItems languageCode:(NSInteger)languageCode completion:(void (^ _Nonnull)(NSArray<HerePlace *> * _Nullable, NSString * _Nullable))completion;
/// Reverse geocoding: look up the place/address at a coordinate.
- (void)searchByCoordinatesWithLatitude:(double)latitude longitude:(double)longitude maxItems:(int32_t)maxItems languageCode:(NSInteger)languageCode completion:(void (^ _Nonnull)(NSArray<HerePlace *> * _Nullable, NSString * _Nullable))completion;
- (void)searchByPlaceIdWithPlaceId:(NSString * _Nonnull)placeId completion:(void (^ _Nonnull)(HerePlace * _Nullable, NSString * _Nullable))completion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible wrapper for Section.
SWIFT_CLASS_NAMED("HereSection")
@interface HereSection : NSObject
@property (nonatomic, strong) HereGeoCoordinates * _Nonnull departure;
@property (nonatomic, strong) HereGeoCoordinates * _Nonnull arrival;
@property (nonatomic, copy) NSArray<HereManeuver *> * _Nullable maneuvers;
@property (nonatomic) NSInteger transportMode;
@property (nonatomic) int32_t lengthInMeters;
@property (nonatomic) double durationInSeconds;
@property (nonatomic, strong) HereGeoPolyline * _Nullable geometry;
- (nonnull instancetype)initWithDeparture:(HereGeoCoordinates * _Nonnull)departure arrival:(HereGeoCoordinates * _Nonnull)arrival maneuvers:(NSArray<HereManeuver *> * _Nullable)maneuvers transportMode:(NSInteger)transportMode lengthInMeters:(int32_t)lengthInMeters durationInSeconds:(double)durationInSeconds geometry:(HereGeoPolyline * _Nullable)geometry OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible wrapper for Size2D (Swift struct → ObjC class).
SWIFT_CLASS_NAMED("HereSize2D")
@interface HereSize2D : NSObject
@property (nonatomic) double width;
@property (nonatomic) double height;
- (nonnull instancetype)initWithWidth:(double)width height:(double)height OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible wrapper for Suggestion.
SWIFT_CLASS_NAMED("HereSuggestion")
@interface HereSuggestion : NSObject
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic) BOOL isPlace;
- (nonnull instancetype)initWithTitle:(NSString * _Nonnull)title id:(NSString * _Nonnull)id isPlace:(BOOL)isPlace OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible delegate for tap gestures.
SWIFT_PROTOCOL_NAMED("HereTapDelegate")
@protocol HereTapDelegate
- (void)onTapWithOriginX:(double)originX originY:(double)originY;
@end

@class HereTrafficFlow;
@class HereTrafficIncident;
/// ObjC-visible wrapper for TrafficEngine.
SWIFT_CLASS_NAMED("HereTrafficEngine")
@interface HereTrafficEngine : NSObject
- (nonnull instancetype)initWithSdkEnginePointer:(int64_t)sdkEnginePointer OBJC_DESIGNATED_INITIALIZER;
- (void)queryFlowWithLatitude:(double)latitude longitude:(double)longitude radiusInMeters:(double)radiusInMeters completion:(void (^ _Nonnull)(NSArray<HereTrafficFlow *> * _Nullable, NSString * _Nullable))completion;
- (void)queryIncidentsWithLatitude:(double)latitude longitude:(double)longitude radiusInMeters:(double)radiusInMeters completion:(void (^ _Nonnull)(NSArray<HereTrafficIncident *> * _Nullable, NSString * _Nullable))completion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible wrapper for TrafficFlow.
SWIFT_CLASS_NAMED("HereTrafficFlow")
@interface HereTrafficFlow : NSObject
@property (nonatomic) double jamFactor;
@property (nonatomic) double speedInMetersPerSecond;
@property (nonatomic) double freeFlowSpeedInMetersPerSecond;
/// Road segment covered by this flow. May be nil if the underlying
/// TrafficFlow has no location (e.g. an empty result row).
@property (nonatomic, strong) HereGeoPolyline * _Nullable location;
- (nonnull instancetype)initWithJamFactor:(double)jamFactor speedInMetersPerSecond:(double)speedInMetersPerSecond freeFlowSpeedInMetersPerSecond:(double)freeFlowSpeedInMetersPerSecond location:(HereGeoPolyline * _Nullable)location OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible wrapper for TrafficIncident.
SWIFT_CLASS_NAMED("HereTrafficIncident")
@interface HereTrafficIncident : NSObject
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull descriptionText;
@property (nonatomic) NSInteger typeRawValue;
@property (nonatomic) NSInteger impactRawValue;
@property (nonatomic) BOOL isRoadClosed;
/// Road segment covered by this incident. Used by the RefApp to
/// drop a marker at the first vertex. May be nil for incidents
/// without geometry.
@property (nonatomic, strong) HereGeoPolyline * _Nullable location;
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id descriptionText:(NSString * _Nonnull)descriptionText typeRawValue:(NSInteger)typeRawValue impactRawValue:(NSInteger)impactRawValue isRoadClosed:(BOOL)isRoadClosed location:(HereGeoPolyline * _Nullable)location OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible wrapper for Waypoint (Swift struct).
SWIFT_CLASS_NAMED("HereWaypoint")
@interface HereWaypoint : NSObject
@property (nonatomic) double latitude;
@property (nonatomic) double longitude;
@property (nonatomic) NSInteger type;
- (nonnull instancetype)initWithLatitude:(double)latitude longitude:(double)longitude type:(NSInteger)type OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Stub class that satisfies the HERE SDK’s optional <code>hsdk-initializeOptional</code>
/// reflection hook. The native SDK does an <code>NSClassFromString("LocationInitializer")</code>
/// lookup at engine init and then calls a class method on the result. The exact
/// selector varies by SDK version and platform: the 4.25.x Explore SDK on iOS
/// calls <code>+opt_initialize:</code> (one argument). If the class is missing OR the
/// selector is missing, the hook logs <code>class LocationInitializer not found</code>
/// (or <code>unrecognized selector sent to class 0x…</code>) and the <code>LoadingView</code> never
/// dismisses, wedging the iOS RefApp on the init splash.
/// <code>ILocationService</code> in the C# layer uses
/// <code>Microsoft.Maui.Devices.Sensors.Geolocation</code> as the primary source
/// (see CLAUDE.md rule 17 — HERE native positioning is not exposed in
/// iOS NativeBridge yet), so the SDK’s own positioning hook is
/// intentionally unused. This stub exists solely to satisfy the
/// reflection lookup so the init hook can complete.
/// The Objective-C class name is <em>exactly</em> <code>LocationInitializer</code> (no
/// <code>Here</code> prefix) because that is the literal string the native SDK
/// passes to <code>NSClassFromString</code>. Do not rename it.
SWIFT_CLASS_NAMED("LocationInitializer")
@interface LocationInitializer : NSObject
/// Class method that the HERE SDK’s optional-init hook actually calls on
/// the resolved <code>LocationInitializer</code> class. Takes one argument (the
/// hook passes whatever it has — typically a settings/options object —
/// and we ignore it). Selector name is <em>exactly</em> <code>opt_initialize:</code> —
/// the trailing colon is part of the selector name.
+ (void)opt_initialize:(id _Nullable)arg;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.3.3 effective-5.10 (swiftlang-6.3.3.1.3 clang-2100.1.1.101)
#ifndef HERESDKEXPLORENATIVEBRIDGE_SWIFT_H
#define HERESDKEXPLORENATIVEBRIDGE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="HereSdkExploreNativeBridge",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="HereSdkExploreNativeBridge",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
/// ObjC-visible wrapper for Address.
SWIFT_CLASS_NAMED("HereAddress")
@interface HereAddress : NSObject
@property (nonatomic, copy) NSString * _Nonnull street;
@property (nonatomic, copy) NSString * _Nonnull houseNumber;
@property (nonatomic, copy) NSString * _Nonnull city;
@property (nonatomic, copy) NSString * _Nonnull district;
@property (nonatomic, copy) NSString * _Nonnull state;
@property (nonatomic, copy) NSString * _Nonnull countryCode;
@property (nonatomic, copy) NSString * _Nonnull countryName;
@property (nonatomic, copy) NSString * _Nonnull postalCode;
- (nonnull instancetype)initWithStreet:(NSString * _Nonnull)street houseNumber:(NSString * _Nonnull)houseNumber city:(NSString * _Nonnull)city district:(NSString * _Nonnull)district state:(NSString * _Nonnull)state countryCode:(NSString * _Nonnull)countryCode countryName:(NSString * _Nonnull)countryName postalCode:(NSString * _Nonnull)postalCode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible wrapper for MapCamera.State (nested struct).
SWIFT_CLASS_NAMED("HereCameraState")
@interface HereCameraState : NSObject
@property (nonatomic) double targetLatitude;
@property (nonatomic) double targetLongitude;
@property (nonatomic) double bearing;
@property (nonatomic) double tilt;
@property (nonatomic) double distanceToTargetInMeters;
@property (nonatomic) double zoomLevel;
- (nonnull instancetype)initWithTargetLatitude:(double)targetLatitude targetLongitude:(double)targetLongitude bearing:(double)bearing tilt:(double)tilt distanceToTargetInMeters:(double)distanceToTargetInMeters zoomLevel:(double)zoomLevel OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible delegate for double tap gestures.
SWIFT_PROTOCOL_NAMED("HereDoubleTapDelegate")
@protocol HereDoubleTapDelegate
- (void)onDoubleTapWithOriginX:(double)originX originY:(double)originY;
@end

@class HereGeoCoordinates;
/// ObjC-visible wrapper for GeoBox.
SWIFT_CLASS_NAMED("HereGeoBox")
@interface HereGeoBox : NSObject
@property (nonatomic, strong) HereGeoCoordinates * _Nonnull southWest;
@property (nonatomic, strong) HereGeoCoordinates * _Nonnull northEast;
- (nonnull instancetype)initWithSouthWest:(HereGeoCoordinates * _Nonnull)southWest northEast:(HereGeoCoordinates * _Nonnull)northEast OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible wrapper for GeoCoordinates (Swift struct → ObjC class).
SWIFT_CLASS_NAMED("HereGeoCoordinates")
@interface HereGeoCoordinates : NSObject
@property (nonatomic) double latitude;
@property (nonatomic) double longitude;
- (nonnull instancetype)initWithLatitude:(double)latitude longitude:(double)longitude OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible wrapper for GeoPolygon.
SWIFT_CLASS_NAMED("HereGeoPolygon")
@interface HereGeoPolygon : NSObject
@property (nonatomic, copy) NSArray<HereGeoCoordinates *> * _Nonnull vertices;
- (nonnull instancetype)initWithVertices:(NSArray<HereGeoCoordinates *> * _Nonnull)vertices OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible wrapper for GeoPolyline.
SWIFT_CLASS_NAMED("HereGeoPolyline")
@interface HereGeoPolyline : NSObject
@property (nonatomic, copy) NSArray<HereGeoCoordinates *> * _Nonnull vertices;
- (nonnull instancetype)initWithVertices:(NSArray<HereGeoCoordinates *> * _Nonnull)vertices OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class HereMapBridgeView;
@protocol HereTapDelegate;
@protocol HereLongPressDelegate;
/// ObjC-visible wrapper for Gestures.
SWIFT_CLASS_NAMED("HereGestures")
@interface HereGestures : NSObject
/// @objc factory — creates from the bridge view which holds the MapView.
- (nonnull instancetype)initWithBridgeView:(HereMapBridgeView * _Nonnull)bridgeView;
- (void)setTapDelegate:(id <HereTapDelegate> _Nullable)delegate;
- (void)setLongPressDelegate:(id <HereLongPressDelegate> _Nullable)delegate;
- (void)setDoubleTapDelegate:(id <HereDoubleTapDelegate> _Nullable)delegate;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible wrapper for InstantiationErrorCode (UInt32 → NSInteger).
typedef SWIFT_ENUM_NAMED(NSInteger, HereInstantiationErrorCode, "HereInstantiationErrorCode", open) {
  HereInstantiationErrorCodeNone = 0,
  HereInstantiationErrorCodeNetworkError = 1,
  HereInstantiationErrorCodeInvalidCredentials = 2,
  HereInstantiationErrorCodeInvalidOptions = 3,
  HereInstantiationErrorCodeAlreadyInitialized = 4,
  HereInstantiationErrorCodeEngineDisposed = 5,
  HereInstantiationErrorCodeInternalError = 6,
};

/// ObjC-visible wrapper for Isoline.
SWIFT_CLASS_NAMED("HereIsoline")
@interface HereIsoline : NSObject
@property (nonatomic) double rangeValue;
@property (nonatomic, copy) NSArray<HereGeoCoordinates *> * _Nonnull polygonVertices;
- (nonnull instancetype)initWithRangeValue:(double)rangeValue polygonVertices:(NSArray<HereGeoCoordinates *> * _Nonnull)polygonVertices OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible isoline result.
SWIFT_CLASS_NAMED("HereIsolineResult")
@interface HereIsolineResult : NSObject
@property (nonatomic, copy) NSString * _Nullable error;
@property (nonatomic, copy) NSArray<HereIsoline *> * _Nullable isolines;
- (nonnull instancetype)initWithError:(NSString * _Nullable)error isolines:(NSArray<HereIsoline *> * _Nullable)isolines OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible wrapper for IsolineRoutingEngine.
SWIFT_CLASS_NAMED("HereIsolineRoutingEngine")
@interface HereIsolineRoutingEngine : NSObject
- (nonnull instancetype)initWithSdkEnginePointer:(int64_t)sdkEnginePointer OBJC_DESIGNATED_INITIALIZER;
/// Calculates an isoline around a center point.
/// \param transportMode 0=Car, 1=Truck, 2=Pedestrian, 3=Bicycle, 4=Scooter (see HereRoutingOptions)
///
/// \param rangeInMeters reachability range in meters
///
/// \param maxPoints maximum polygon points; 0 means SDK default
///
- (void)calculateIsolineWithCenterLatitude:(double)centerLatitude centerLongitude:(double)centerLongitude transportMode:(NSInteger)transportMode rangeInMeters:(int32_t)rangeInMeters maxPoints:(int32_t)maxPoints completion:(void (^ _Nonnull)(HereIsolineResult * _Nonnull))completion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible wrapper for Location (Swift struct → ObjC class).
SWIFT_CLASS_NAMED("HereLocation")
@interface HereLocation : NSObject
@property (nonatomic) double latitude;
@property (nonatomic) double longitude;
@property (nonatomic) double speedInMetersPerSecond;
@property (nonatomic) double bearingInDegrees;
@property (nonatomic) int64_t timestampInMilliseconds;
- (nonnull instancetype)initWithLatitude:(double)latitude longitude:(double)longitude speedInMetersPerSecond:(double)speedInMetersPerSecond bearingInDegrees:(double)bearingInDegrees timestampInMilliseconds:(int64_t)timestampInMilliseconds OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible delegate for long press gestures.
/// Includes gesture state (begin/update/end) as an integer: 0=begin, 1=update, 2=end.
SWIFT_PROTOCOL_NAMED("HereLongPressDelegate")
@protocol HereLongPressDelegate
- (void)onLongPressWithState:(NSInteger)state originX:(double)originX originY:(double)originY;
@end

/// ObjC-visible wrapper for Maneuver.
SWIFT_CLASS_NAMED("HereManeuver")
@interface HereManeuver : NSObject
@property (nonatomic, strong) HereGeoCoordinates * _Nonnull coordinates;
@property (nonatomic) NSInteger action;
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic) int32_t lengthInMeters;
@property (nonatomic) double durationInSeconds;
@property (nonatomic) double turnAngleInDegrees;
- (nonnull instancetype)initWithCoordinates:(HereGeoCoordinates * _Nonnull)coordinates action:(NSInteger)action text:(NSString * _Nullable)text lengthInMeters:(int32_t)lengthInMeters durationInSeconds:(double)durationInSeconds turnAngleInDegrees:(double)turnAngleInDegrees OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIColor;
/// ObjC-visible wrapper for MapArrow.
SWIFT_CLASS_NAMED("HereMapArrow")
@interface HereMapArrow : NSObject
- (nonnull instancetype)initWithVertices:(NSArray<HereGeoCoordinates *> * _Nonnull)vertices widthInPixels:(double)widthInPixels color:(UIColor * _Nonnull)color OBJC_DESIGNATED_INITIALIZER;
- (void)addToMapView:(HereMapBridgeView * _Nonnull)mapView;
- (void)removeFromMapView:(HereMapBridgeView * _Nonnull)mapView;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIView;
/// ObjC-visible UIView wrapper that owns a HERE MapView.
/// C# uses this as the platform view for the MAUI handler.
/// Other NativeBridge wrappers (HereMapCamera, HereMapScene, HereGestures)
/// extract MapView/mapScene/camera/gestures from this bridge view.
SWIFT_CLASS_NAMED("HereMapBridgeView")
@interface HereMapBridgeView : NSObject
/// @objc factory — C# calls this to create a bridge that owns the MapView.
+ (HereMapBridgeView * _Nonnull)create SWIFT_WARN_UNUSED_RESULT;
/// Expose the MapView as a UIView for C# handlers.
@property (nonatomic, readonly, strong) UIView * _Nullable platformView;
/// Convert screen coordinates to geo coordinates.
- (HereGeoCoordinates * _Nullable)viewToGeoCoordinatesWithOriginX:(double)originX originY:(double)originY SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol HereMapCameraDelegate;
/// ObjC-visible wrapper for MapCamera.
SWIFT_CLASS_NAMED("HereMapCamera")
@interface HereMapCamera : NSObject
/// @objc factory — creates from the bridge view which holds the MapView.
- (nonnull instancetype)initWithBridgeView:(HereMapBridgeView * _Nonnull)bridgeView;
@property (nonatomic, readonly, strong) HereCameraState * _Nonnull state;
- (void)setTarget:(HereGeoCoordinates * _Nonnull)coordinates;
- (void)setTarget:(HereGeoCoordinates * _Nonnull)coordinates zoomLevel:(double)zoomLevel;
- (void)addDelegate:(id <HereMapCameraDelegate> _Nonnull)delegate;
- (void)removeDelegate;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible delegate for MapCamera updates.
SWIFT_PROTOCOL_NAMED("HereMapCameraDelegate")
@protocol HereMapCameraDelegate
@optional
- (void)onMapCameraUpdated:(HereCameraState * _Nonnull)cameraState;
@end

/// ObjC-visible wrapper for MapMarker.
SWIFT_CLASS_NAMED("HereMapMarker")
@interface HereMapMarker : NSObject
@property (nonatomic) double latitude;
@property (nonatomic) double longitude;
@property (nonatomic, copy) NSString * _Nullable imageName;
- (nonnull instancetype)initWithLatitude:(double)latitude longitude:(double)longitude OBJC_DESIGNATED_INITIALIZER;
/// Create with image name (for MapScene-based add/remove).
- (nonnull instancetype)initWithLatitude:(double)latitude longitude:(double)longitude imageName:(NSString * _Nonnull)imageName OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible wrapper for MapMarker3D.
/// Supports both image-based and model-based 3D markers.
SWIFT_CLASS_NAMED("HereMapMarker3D")
@interface HereMapMarker3D : NSObject
@property (nonatomic) double bearing;
@property (nonatomic) double scale;
/// Create a 3D marker with an image (billboard-style).
- (nonnull instancetype)initWithLatitude:(double)latitude longitude:(double)longitude imageName:(NSString * _Nonnull)imageName width:(int32_t)width height:(int32_t)height scale:(double)scale OBJC_DESIGNATED_INITIALIZER;
- (void)addToMapView:(HereMapBridgeView * _Nonnull)mapView;
- (void)removeFromMapView:(HereMapBridgeView * _Nonnull)mapView;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible wrapper for MapPolygon.
SWIFT_CLASS_NAMED("HereMapPolygon")
@interface HereMapPolygon : NSObject
@property (nonatomic) int32_t drawOrder;
- (nonnull instancetype)initWithVertices:(NSArray<HereGeoCoordinates *> * _Nonnull)vertices fillColor:(UIColor * _Nonnull)fillColor OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithVertices:(NSArray<HereGeoCoordinates *> * _Nonnull)vertices fillColor:(UIColor * _Nonnull)fillColor outlineColor:(UIColor * _Nonnull)outlineColor outlineWidthInPixels:(double)outlineWidthInPixels OBJC_DESIGNATED_INITIALIZER;
- (void)addToMapView:(HereMapBridgeView * _Nonnull)mapView;
- (void)removeFromMapView:(HereMapBridgeView * _Nonnull)mapView;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible wrapper for MapPolyline.
/// MapPolyline uses the Representation pattern for styling.
SWIFT_CLASS_NAMED("HereMapPolyline")
@interface HereMapPolyline : NSObject
@property (nonatomic) int32_t drawOrder;
/// Creates a solid-color polyline with the given vertices, color, and width.
- (nonnull instancetype)initWithVertices:(NSArray<HereGeoCoordinates *> * _Nonnull)vertices color:(UIColor * _Nonnull)color widthInPixels:(double)widthInPixels OBJC_DESIGNATED_INITIALIZER;
- (void)addToMapView:(HereMapBridgeView * _Nonnull)mapView;
- (void)removeFromMapView:(HereMapBridgeView * _Nonnull)mapView;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_ENUM_FWD_DECL(NSInteger, HereMapScheme)
@protocol HereSceneLoadCallback;
/// ObjC-visible wrapper for MapScene.
SWIFT_CLASS_NAMED("HereMapScene")
@interface HereMapScene : NSObject
/// @objc factory — creates from the bridge view which holds the MapView.
- (nonnull instancetype)initWithBridgeView:(HereMapBridgeView * _Nonnull)bridgeView;
- (void)loadScene:(enum HereMapScheme)scheme;
- (void)setCallback:(id <HereSceneLoadCallback> _Nonnull)callback;
- (void)addMapMarker:(HereMapMarker * _Nonnull)marker;
- (void)removeMapMarker:(HereMapMarker * _Nonnull)marker;
- (void)addMapMarker3D:(HereMapMarker3D * _Nonnull)marker;
- (void)removeMapMarker3D:(HereMapMarker3D * _Nonnull)marker;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible NSInteger enum wrapper for MapScheme (which is UInt32-backed in Swift).
typedef SWIFT_ENUM_NAMED(NSInteger, HereMapScheme, "HereMapScheme", open) {
  HereMapSchemeNormalDay = 0,
  HereMapSchemeNormalNight = 1,
  HereMapSchemeSatellite = 2,
  HereMapSchemeHybridDay = 3,
  HereMapSchemeHybridNight = 4,
  HereMapSchemeLiteDay = 5,
  HereMapSchemeLiteNight = 6,
  HereMapSchemeLiteHybridDay = 7,
  HereMapSchemeLiteHybridNight = 8,
  HereMapSchemeLogisticsDay = 9,
  HereMapSchemeLogisticsNight = 10,
  HereMapSchemeLogisticsHybridDay = 11,
  HereMapSchemeLogisticsHybridNight = 12,
  HereMapSchemeRoadNetworkDay = 13,
  HereMapSchemeRoadNetworkNight = 14,
};

/// ObjC-visible wrapper for Place (search result).
SWIFT_CLASS_NAMED("HerePlace")
@interface HerePlace : NSObject
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic) double latitude;
@property (nonatomic) double longitude;
@property (nonatomic, strong) HereAddress * _Nullable address;
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id title:(NSString * _Nonnull)title latitude:(double)latitude longitude:(double)longitude address:(HereAddress * _Nullable)address OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible wrapper for Point2D (Swift struct → ObjC class).
SWIFT_CLASS_NAMED("HerePoint2D")
@interface HerePoint2D : NSObject
@property (nonatomic) double x;
@property (nonatomic) double y;
- (nonnull instancetype)initWithX:(double)x y:(double)y OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class HereSection;
/// ObjC-visible wrapper for Route.
SWIFT_CLASS_NAMED("HereRoute")
@interface HereRoute : NSObject
@property (nonatomic) int32_t lengthInMeters;
@property (nonatomic) double durationInSeconds;
@property (nonatomic, copy) NSString * _Nullable routeHandle;
@property (nonatomic, copy) NSArray<HereSection *> * _Nullable sections;
@property (nonatomic, strong) HereGeoPolyline * _Nullable geometry;
- (nonnull instancetype)initWithLengthInMeters:(int32_t)lengthInMeters durationInSeconds:(double)durationInSeconds routeHandle:(NSString * _Nullable)routeHandle sections:(NSArray<HereSection *> * _Nullable)sections geometry:(HereGeoPolyline * _Nullable)geometry OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible route result.
SWIFT_CLASS_NAMED("HereRouteResult")
@interface HereRouteResult : NSObject
@property (nonatomic, copy) NSString * _Nullable error;
@property (nonatomic, copy) NSArray<HereRoute *> * _Nullable routes;
- (nonnull instancetype)initWithError:(NSString * _Nullable)error routes:(NSArray<HereRoute *> * _Nullable)routes OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class HereWaypoint;
@class HereRoutingOptions;
/// ObjC-visible wrapper for RoutingEngine.
SWIFT_CLASS_NAMED("HereRoutingEngine")
@interface HereRoutingEngine : NSObject
- (nonnull instancetype)initWithSdkEnginePointer:(int64_t)sdkEnginePointer OBJC_DESIGNATED_INITIALIZER;
- (void)calculateRouteWithWaypoints:(NSArray<HereWaypoint *> * _Nonnull)waypoints options:(HereRoutingOptions * _Nonnull)options completion:(void (^ _Nonnull)(HereRouteResult * _Nonnull))completion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible wrapper for RoutingOptions.
/// Uses TransportSpecification (the new v4.28+ pattern).
SWIFT_CLASS_NAMED("HereRoutingOptions")
@interface HereRoutingOptions : NSObject
@property (nonatomic) NSInteger transportMode;
- (nonnull instancetype)initWithTransportMode:(NSInteger)transportMode OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Callback for scene load completion.
SWIFT_PROTOCOL_NAMED("HereSceneLoadCallback")
@protocol HereSceneLoadCallback
- (void)onSceneLoaded:(enum HereMapScheme)scheme;
- (void)onSceneLoadFailed:(NSString * _Nonnull)error;
@end

@class HereSdkOptions;
/// ObjC-visible wrapper for HERE SDK engine initialization.
SWIFT_CLASS_NAMED("HereSdkEngine")
@interface HereSdkEngine : NSObject
+ (void)initialize:(HereSdkOptions * _Nonnull)options;
+ (void)shutdown;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// ObjC-visible wrapper for HERE SDK options (initialization).
SWIFT_CLASS_NAMED("HereSdkOptions")
@interface HereSdkOptions : NSObject
@property (nonatomic, copy) NSString * _Nonnull accessKeyId;
@property (nonatomic, copy) NSString * _Nonnull accessKeySecret;
@property (nonatomic, copy) NSString * _Nullable cachePath;
- (nonnull instancetype)initWithAccessKeyId:(NSString * _Nonnull)accessKeyId accessKeySecret:(NSString * _Nonnull)accessKeySecret cachePath:(NSString * _Nullable)cachePath OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class HereSuggestion;
/// ObjC-visible wrapper for SearchEngine.
SWIFT_CLASS_NAMED("HereSearchEngine")
@interface HereSearchEngine : NSObject
- (nonnull instancetype)initWithSdkEnginePointer:(int64_t)sdkEnginePointer OBJC_DESIGNATED_INITIALIZER;
- (void)searchByTextWithQuery:(NSString * _Nonnull)query latitude:(double)latitude longitude:(double)longitude maxItems:(int32_t)maxItems languageCode:(NSInteger)languageCode completion:(void (^ _Nonnull)(NSArray<HerePlace *> * _Nullable, NSString * _Nullable))completion;
- (void)searchByCategoryWithCategoryId:(NSString * _Nonnull)categoryId latitude:(double)latitude longitude:(double)longitude maxItems:(int32_t)maxItems languageCode:(NSInteger)languageCode completion:(void (^ _Nonnull)(NSArray<HerePlace *> * _Nullable, NSString * _Nullable))completion;
- (void)suggestWithQuery:(NSString * _Nonnull)query latitude:(double)latitude longitude:(double)longitude maxItems:(int32_t)maxItems languageCode:(NSInteger)languageCode completion:(void (^ _Nonnull)(NSArray<HereSuggestion *> * _Nullable, NSString * _Nullable))completion;
- (void)searchByAddressWithQuery:(NSString * _Nonnull)query latitude:(double)latitude longitude:(double)longitude maxItems:(int32_t)maxItems languageCode:(NSInteger)languageCode completion:(void (^ _Nonnull)(NSArray<HerePlace *> * _Nullable, NSString * _Nullable))completion;
/// Reverse geocoding: look up the place/address at a coordinate.
- (void)searchByCoordinatesWithLatitude:(double)latitude longitude:(double)longitude maxItems:(int32_t)maxItems languageCode:(NSInteger)languageCode completion:(void (^ _Nonnull)(NSArray<HerePlace *> * _Nullable, NSString * _Nullable))completion;
- (void)searchByPlaceIdWithPlaceId:(NSString * _Nonnull)placeId completion:(void (^ _Nonnull)(HerePlace * _Nullable, NSString * _Nullable))completion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible wrapper for Section.
SWIFT_CLASS_NAMED("HereSection")
@interface HereSection : NSObject
@property (nonatomic, strong) HereGeoCoordinates * _Nonnull departure;
@property (nonatomic, strong) HereGeoCoordinates * _Nonnull arrival;
@property (nonatomic, copy) NSArray<HereManeuver *> * _Nullable maneuvers;
@property (nonatomic) NSInteger transportMode;
@property (nonatomic) int32_t lengthInMeters;
@property (nonatomic) double durationInSeconds;
@property (nonatomic, strong) HereGeoPolyline * _Nullable geometry;
- (nonnull instancetype)initWithDeparture:(HereGeoCoordinates * _Nonnull)departure arrival:(HereGeoCoordinates * _Nonnull)arrival maneuvers:(NSArray<HereManeuver *> * _Nullable)maneuvers transportMode:(NSInteger)transportMode lengthInMeters:(int32_t)lengthInMeters durationInSeconds:(double)durationInSeconds geometry:(HereGeoPolyline * _Nullable)geometry OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible wrapper for Size2D (Swift struct → ObjC class).
SWIFT_CLASS_NAMED("HereSize2D")
@interface HereSize2D : NSObject
@property (nonatomic) double width;
@property (nonatomic) double height;
- (nonnull instancetype)initWithWidth:(double)width height:(double)height OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible wrapper for Suggestion.
SWIFT_CLASS_NAMED("HereSuggestion")
@interface HereSuggestion : NSObject
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic) BOOL isPlace;
- (nonnull instancetype)initWithTitle:(NSString * _Nonnull)title id:(NSString * _Nonnull)id isPlace:(BOOL)isPlace OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible delegate for tap gestures.
SWIFT_PROTOCOL_NAMED("HereTapDelegate")
@protocol HereTapDelegate
- (void)onTapWithOriginX:(double)originX originY:(double)originY;
@end

@class HereTrafficFlow;
@class HereTrafficIncident;
/// ObjC-visible wrapper for TrafficEngine.
SWIFT_CLASS_NAMED("HereTrafficEngine")
@interface HereTrafficEngine : NSObject
- (nonnull instancetype)initWithSdkEnginePointer:(int64_t)sdkEnginePointer OBJC_DESIGNATED_INITIALIZER;
- (void)queryFlowWithLatitude:(double)latitude longitude:(double)longitude radiusInMeters:(double)radiusInMeters completion:(void (^ _Nonnull)(NSArray<HereTrafficFlow *> * _Nullable, NSString * _Nullable))completion;
- (void)queryIncidentsWithLatitude:(double)latitude longitude:(double)longitude radiusInMeters:(double)radiusInMeters completion:(void (^ _Nonnull)(NSArray<HereTrafficIncident *> * _Nullable, NSString * _Nullable))completion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible wrapper for TrafficFlow.
SWIFT_CLASS_NAMED("HereTrafficFlow")
@interface HereTrafficFlow : NSObject
@property (nonatomic) double jamFactor;
@property (nonatomic) double speedInMetersPerSecond;
@property (nonatomic) double freeFlowSpeedInMetersPerSecond;
/// Road segment covered by this flow. May be nil if the underlying
/// TrafficFlow has no location (e.g. an empty result row).
@property (nonatomic, strong) HereGeoPolyline * _Nullable location;
- (nonnull instancetype)initWithJamFactor:(double)jamFactor speedInMetersPerSecond:(double)speedInMetersPerSecond freeFlowSpeedInMetersPerSecond:(double)freeFlowSpeedInMetersPerSecond location:(HereGeoPolyline * _Nullable)location OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible wrapper for TrafficIncident.
SWIFT_CLASS_NAMED("HereTrafficIncident")
@interface HereTrafficIncident : NSObject
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull descriptionText;
@property (nonatomic) NSInteger typeRawValue;
@property (nonatomic) NSInteger impactRawValue;
@property (nonatomic) BOOL isRoadClosed;
/// Road segment covered by this incident. Used by the RefApp to
/// drop a marker at the first vertex. May be nil for incidents
/// without geometry.
@property (nonatomic, strong) HereGeoPolyline * _Nullable location;
- (nonnull instancetype)initWithId:(NSString * _Nonnull)id descriptionText:(NSString * _Nonnull)descriptionText typeRawValue:(NSInteger)typeRawValue impactRawValue:(NSInteger)impactRawValue isRoadClosed:(BOOL)isRoadClosed location:(HereGeoPolyline * _Nullable)location OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// ObjC-visible wrapper for Waypoint (Swift struct).
SWIFT_CLASS_NAMED("HereWaypoint")
@interface HereWaypoint : NSObject
@property (nonatomic) double latitude;
@property (nonatomic) double longitude;
@property (nonatomic) NSInteger type;
- (nonnull instancetype)initWithLatitude:(double)latitude longitude:(double)longitude type:(NSInteger)type OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Stub class that satisfies the HERE SDK’s optional <code>hsdk-initializeOptional</code>
/// reflection hook. The native SDK does an <code>NSClassFromString("LocationInitializer")</code>
/// lookup at engine init and then calls a class method on the result. The exact
/// selector varies by SDK version and platform: the 4.25.x Explore SDK on iOS
/// calls <code>+opt_initialize:</code> (one argument). If the class is missing OR the
/// selector is missing, the hook logs <code>class LocationInitializer not found</code>
/// (or <code>unrecognized selector sent to class 0x…</code>) and the <code>LoadingView</code> never
/// dismisses, wedging the iOS RefApp on the init splash.
/// <code>ILocationService</code> in the C# layer uses
/// <code>Microsoft.Maui.Devices.Sensors.Geolocation</code> as the primary source
/// (see CLAUDE.md rule 17 — HERE native positioning is not exposed in
/// iOS NativeBridge yet), so the SDK’s own positioning hook is
/// intentionally unused. This stub exists solely to satisfy the
/// reflection lookup so the init hook can complete.
/// The Objective-C class name is <em>exactly</em> <code>LocationInitializer</code> (no
/// <code>Here</code> prefix) because that is the literal string the native SDK
/// passes to <code>NSClassFromString</code>. Do not rename it.
SWIFT_CLASS_NAMED("LocationInitializer")
@interface LocationInitializer : NSObject
/// Class method that the HERE SDK’s optional-init hook actually calls on
/// the resolved <code>LocationInitializer</code> class. Takes one argument (the
/// hook passes whatever it has — typically a settings/options object —
/// and we ignore it). Selector name is <em>exactly</em> <code>opt_initialize:</code> —
/// the trailing colon is part of the selector name.
+ (void)opt_initialize:(id _Nullable)arg;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
