using Foundation;

namespace Here.Explore.iOS
{
    // iOS binding API definitions will be generated by Objective-Sharpie
    // and then manually fixed up.
    // See scripts/bind-ios.sh for the generation process.
}